app:
  name: "Ember Game Engine" # Name of the executable
window:
  width: 1280
  height: 720
  vsync: false
  refresh-rate: -1 # -1 Means default refresh rate for monitor
  retina: false   # For retina displays
  # WINDOWED            = 0
  # FULLSCREEN          = 1
  # WINDOWED FULSCREEN  = 2
  window-mode: 0
  # Only applied for fullscreen, overrides the current resolution
  maximize: false
  resizable: false # Can't change this afterwards
  monitor: 0 # Monitor to be displayed on